In [8]:
import numpy as np

#first numpy crash course lecture

In [3]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [12]:
# create an array with (ini, to-end, with-this-pace)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
# np.zeros(lines,columns)
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [19]:
# works the same way as np.zeros but put ones instead of zeros
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
# np.linspace(start, end, number of points between)
np.linspace(0,11,5)

array([  0.  ,   2.75,   5.5 ,   8.25,  11.  ])

In [26]:
# randint(low, high=None, size=None, dtype='l')

np.random.randint(0,10,(3,3))

array([[3, 9, 8],
       [1, 3, 3],
       [6, 8, 1]])

In [56]:
#by setting the seed generator you can be sure to get the same value every time you execute
np.random.seed(101)

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [30]:
np.random.randint(0,100,10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [44]:
np.random.seed(101)

arr = np.random.randint(0,100,(10))

In [45]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [46]:
arr.max()

95

In [47]:
arr.min()

9

In [48]:
arr.mean()

60.799999999999997

In [57]:
# gives back the indices of the maximum values of a given axis -- REALLY IMPORTANT - remember neural nets**
arr.argmax()

0

In [51]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [52]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [53]:
mat = np.arange(0,100).reshape(10,10)

In [54]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
mat[0,1]

1

In [60]:
# fetching 43 in the matrix
line = 4
column = 3

mat[line,column]

43

In [63]:
# all the rows in the first column
# remember the formula matrix[rows,cols]
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# return a single row- row 5
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [67]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
# slices off rows only to the third item of the row
# first 0:3 is to get only the first 3 rows
# second 0:3 will get only 3 items/columns of each row
mat[0:30:3,0:3]


array([[ 0,  1,  2],
       [30, 31, 32],
       [60, 61, 62],
       [90, 91, 92]])

In [76]:
# masking - get the values where the matrix matches the expression, returning a matrix of booleans
mymat = mat > 50 

In [75]:
mat[mymat]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])