   # Scikit Learn Preprocessing

In [3]:
 import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = np.random.randint(0,100,(10,2))

In [7]:
data

array([[66, 38],
       [58, 65],
       [67, 68],
       [ 1, 46],
       [27, 67],
       [65, 56],
       [66, 71],
       [43,  2],
       [38, 21],
       [10, 43]])

In [8]:
scaler_model = MinMaxScaler()

In [9]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [16]:
scaler_model.fit(data)

/home/vinicius/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaler_model.transform(data)

array([[ 0.98484848,  0.52173913],
       [ 0.86363636,  0.91304348],
       [ 1.        ,  0.95652174],
       [ 0.        ,  0.63768116],
       [ 0.39393939,  0.94202899],
       [ 0.96969697,  0.7826087 ],
       [ 0.98484848,  1.        ],
       [ 0.63636364,  0.        ],
       [ 0.56060606,  0.27536232],
       [ 0.13636364,  0.5942029 ]])

In [18]:
scaler_model.fit_transform(data)

/home/vinicius/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.98484848,  0.52173913],
       [ 0.86363636,  0.91304348],
       [ 1.        ,  0.95652174],
       [ 0.        ,  0.63768116],
       [ 0.39393939,  0.94202899],
       [ 0.96969697,  0.7826087 ],
       [ 0.98484848,  1.        ],
       [ 0.63636364,  0.        ],
       [ 0.56060606,  0.27536232],
       [ 0.13636364,  0.5942029 ]])

In [19]:
import pandas as pd

In [22]:
mydata=np.random.randint(0,101,(50,4))

In [23]:
mydata

array([[ 14,  55,  16,  25],
       [ 82,  77,  84,  94],
       [ 68,   4,  63,  21],
       [ 50,  73,   3,  31],
       [ 68,  38,  87,  10],
       [ 64,  82,  78,  31],
       [ 38,  55,  49,   5],
       [ 92,  86,  25,  64],
       [ 21,  57,  33,  14],
       [ 42,  54,  69,  38],
       [ 65,  34, 100,  55],
       [ 68,   9,  83,  61],
       [ 88,  93,  91,  89],
       [ 12,  22,  49,  11],
       [ 77,  74,  46,  82],
       [ 30,   0,  71,  68],
       [ 80,  63,  91,  59],
       [ 25,  78,  12,  87],
       [ 71,  27,  77,  69],
       [ 21,  13,  51,  23],
       [ 33,  76,  21,  91],
       [ 27,  40,  65,  83],
       [ 35,  30,  26,  39],
       [ 18,  75,  23,  27],
       [ 27,  99,   5,  93],
       [ 63,  51,  11,  66],
       [ 85,  56,  65,  30],
       [ 73,  94,  42,  42],
       [ 28,  68,  25,   9],
       [ 61,   6,  53,  52],
       [100,   7,   3,   7],
       [  5,  18,  30,  97],
       [ 56,  21,  99,   9],
       [ 30,  37,  58,   0],
       [ 11,  

In [30]:
df = pd.DataFrame(data=mydata, columns=['F1','F2','F3','LABEL'])

In [31]:
df

F1  F2   F3  LABEL
0    14  55   16     25
1    82  77   84     94
2    68   4   63     21
3    50  73    3     31
4    68  38   87     10
5    64  82   78     31
6    38  55   49      5
7    92  86   25     64
8    21  57   33     14
9    42  54   69     38
10   65  34  100     55
11   68   9   83     61
12   88  93   91     89
13   12  22   49     11
14   77  74   46     82
15   30   0   71     68
16   80  63   91     59
17   25  78   12     87
18   71  27   77     69
19   21  13   51     23
20   33  76   21     91
21   27  40   65     83
22   35  30   26     39
23   18  75   23     27
24   27  99    5     93
25   63  51   11     66
26   85  56   65     30
27   73  94   42     42
28   28  68   25      9
29   61   6   53     52
30  100   7    3      7
31    5  18   30     97
32   56  21   99      9
33   30  37   58      0
34   11  69   56     32
35   45  52   30     88
36   78  59   60     74
37   98  26   80      9
38    8  95   31      9
39   55  97    9     55
40   41  84   96     94
41   91  78   74     45
42   20  57   64      9
43   49  58   98     75
44   53  24   28     98
45   20   7   79     93
46   94  99   38     73
47    2  58    2     25
48   53  65   42     74
49   43  22   98     40

In [33]:
X = df[['F1','F2','F3']]

In [34]:
Y = df['LABEL']

In [35]:
from sklearn.model_selection import train_test_split

In [40]:
 X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [41]:
X_train.shape

(35, 3)

In [43]:
X_test.shape

(15, 3)