# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


## Creating constants

In [ ]:
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


## Creating a session    

In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'HelloWorld'


## Addition in Tensorflow

In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a + b


<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [16]:
result

30

In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [20]:
myzeros = tf.zeros((4,4))

In [21]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [23]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [24]:
myops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

# Calling session in multiple cells

In [25]:
sess = tf.InteractiveSession()

In [27]:
#Now I can continue interacting with the session started in the cell above 
for op in myops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.49814847 -0.17010468 -0.36668459  2.14292765]
 [ 0.20308197  1.31828749 -1.1848675  -0.09432849]
 [ 0.95523429  0.6282388  -0.37772843  0.31073508]
 [-0.50804877  0.07849399 -0.32819584  0.69599867]]


[[ 0.19437873  0.39852476  0.52062905  0.26748145]
 [ 0.28569126  0.63586056  0.26109481  0.85000241]
 [ 0.02526307  0.20932388  0.78105366  0.79207361]
 [ 0.92993033  0.24453712  0.18862438  0.61513579]]




In [28]:
a = tf.constant([[1,2],
                 [3,4] ])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([ [10], [100] ])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result = tf.matmul(a,b)

In [34]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [35]:
result.eval()

array([[210],
       [430]], dtype=int32)